"use strict";

if (document.getElementById('redPill') != null) {
  window.onload = function () {
    createHeader();
    createContent();
    createFooter();
  };
  var createHeader = function createHeader() {
    var header = document.createElement("header");
    console.log(header);
    document.body.appendChild(header);
    var tableNav = document.createElement("table");
    tableNav.cellPadding = "10";
    tableNav.cellSpacing = "5";
    header.appendChild(tableNav);
    var thLeft = document.createElement("th");
    tableNav.appendChild(thLeft);
    var h1Left = document.createElement("h1");
    thLeft.appendChild(h1Left);
    var aLeft = document.createElement("a");
    aLeft.innerText = "⇜";
    aLeft.setAttribute('href', "pick-a-pill.html");
    h1Left.appendChild(aLeft);
    var hr = document.createElement("hr");
    header.appendChild(hr);
  };
  var createContent = function createContent() {
    var divContainer = document.createElement("div");
    console.log(divContainer);
    divContainer.className = "container";
    document.body.appendChild(divContainer);
    var tableText = document.createElement("table");
    divContainer.appendChild(tableText);
    var tr1 = document.createElement("tr");
    tableText.appendChild(tr1);
    var th1 = document.createElement("th");
    th1.colSpan = "2";
    tr1.appendChild(th1);
    var img = document.createElement("img");
    img.setAttribute('src', "https://i.pinimg.com/originals/7d/09/a4/7d09a485cb23ebed6cb999e0f4302dd6.gif");
    img.width = "122";
    img.height = "122";
    th1.appendChild(img);
    var tr2 = document.createElement("tr");
    tableText.appendChild(tr2);
    var th2 = document.createElement("th");
    th2.colSpan = "2";
    tr2.appendChild(th2);
    var h2 = document.createElement("h2");
    h2.innerText = "Ahora tienes superpoderes";
    th2.appendChild(h2);
    var h3 = document.createElement("h3");
    h3.innerText = "¿Qué quieres hacer con ellos?";
    th2.appendChild(h3);
    var td1 = document.createElement("td");
    tableText.appendChild(td1);
    var h4One = document.createElement("h4");
    td1.appendChild(h4One);
    var a1 = document.createElement("a");
    a1.setAttribute('href', "you.html");
    a1.innerText = "Usarlos para ti";
    h4One.appendChild(a1);
    var td2 = document.createElement("td");
    tableText.appendChild(td2);
    var h4Two = document.createElement("h4");
    td2.appendChild(h4Two);
    var a2 = document.createElement("a");
    a2.setAttribute('href', "everyone.html");
    a2.innerText = "Usarlos para los demás";
    h4Two.appendChild(a2);
    var br = document.createElement("br");
    divContainer.appendChild(br);
  };
  var createFooter = function createFooter() {
    var footer = document.createElement("footer");
    console.log(footer);
    document.body.appendChild(footer);
    var hr = document.createElement("hr");
    footer.appendChild(hr);
    var progressBar = document.createElement("progress");
    progressBar.value = "20";
    progressBar.max = "100";
    footer.appendChild(progressBar);
    var iPage = document.createElement("i");
    iPage.className = "footerText";
    iPage.innerText = "~ 2 ~";
    footer.appendChild(iPage);
    var br = document.createElement("br");
    footer.appendChild(br);
  };
}